### ISSUE TITLE
The 1.6 update does not work

### ISSUE THREAD

**Issue by BlackPearl01** [JMSDOnline/quick-box#16]
Hi !

I tried to update my QuickBox to 1.6, all seems be OK (in CLI) but nothing change on the interface of QuickBox (no widget server load, no widget in real time torrents).

Any idea why ? Thanks :+1: 
![quickbox update](https://cloud.githubusercontent.com/assets/16657045/12464489/79916cb8-bfc9-11e5-9f19-404685ccbf10.png)

**Comment by JMSDOnline** [comment]
Currently I am turning everything over to using the releases API. I think that version 1.6.0 left out the dashboard updates. However, the reason for this is that I recently received some really good feedback from a group and I have been working incredibly hard on implementing the additional features. Since it is a rather large release and I will be using the release api... I have held off on it. I am hoping that within the next week this massive version update will be completed... being one person and having a blizzard of ideas coming my way... It could take a bit longer.

However, I think you'll find it worth (at least I hope) :wink: 

Here is a preview I just now published on youtube:
[Quick Box - more than a script - Update Preview](https://www.youtube.com/watch?v=_-adKCEE81k)

**Comment by BlackPearl01** [comment]
WTF ! The update will be awesome ! Can't wait to upgrade !

**Comment by JMSDOnline** [comment]
:smile: Awesome, I definitely think you'll love it. There are some additional features the video doesn't show that will (at least I will attempt to add) be added. Like SyncThing, SickRage and working on CakeBox. If those things are taking too long to put out another release, they'll come with the next version.
